bestshaper/apps/urls.py
from django.conf.urls import url
from . import views

from rest_framework import routers
from .views import UserViewSet, BrassiereViewSet

urlpatterns = [
    url(r'^$', views.index, name='index',),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^sign_up_done/$', views.sign_up_done, name='sign_up_done'),
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^bra_admin/$', views.bra_admin, name='bra_admin'),
]


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'brassieres', BrassiereViewSet)

bestshaper/bestshaper/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.urls import router as apps_router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.urls', namespace='login')),
    url(r'^api/', include(apps_router.urls)),
]

bestshaper/apps/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=32)
    nick_name = models.CharField(max_length=10)
    password = models.CharField(max_length=10)
    mail = models.EmailField

class Brassiere(models.Model):
    bra_name = models.CharField(max_length=32)
    bra_started_at = models.DateTimeField()
    wash_num = models.IntegerField()
    user = models.ForeignKey(User, related_name='bras')


# class Entry(models.Model):
#     STATUS_DRAFT = "draft"
#     STATUS_PUBLIC = "public"
#     STATUS_SET = (
#         (STATUS_DRAFT, "下書き"),
#         (STATUS_PUBLIC, "公開中"),
#     )
#     title = models.CharField(max_length=128)
#     body = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     status = models.CharField(choices=STATUS_SET, default=STATUS_DRAFT, max_length=8)
#     author = models.ForeignKey(User, related_name='entries')

bestshaper/apps/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from rest_framework import viewsets, filters

from .forms import LoginForm

from .models import User, Brassiere
from .serializer import UserSerializer, BrassiereSerializer



class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class BrassiereViewSet(viewsets.ModelViewSet):
    queryset = Brassiere.objects.all()
    serializer_class = BrassiereSerializer



def index(request):
    return render(request, 'index.html')

def sign_up(request):
    if request.method == 'POST':  # フォームが提出された
        form = LoginForm(request.POST)  # POST データの束縛フォーム
        if form.is_valid():  # バリデーションを通った
            User.objects.create(**form.cleaned_data)
            return redirect('apps:sign_up_done')  # POST 後のリダイレクト
    else:
        form = LoginForm()  # 非束縛フォーム
        d = {
            'form': form,
        }
        return render(request, 'sign_up.html', d)

def sign_up_done(request):
    return render(request, 'sign_up_done.html')

def sign_in(request):
    return render(request, 'sign_in.html')

def bra_admin(request):
    bra = User.objects.get()
    return render(request, 'bra_admin.html')

bestshaper/templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

bestshaper/templates/index.html
{% extends "base.html" %}

{% block body %}
    <div>index</div>

    <a href="{% url 'login:sign_up' %}">sign_up</a><br>
    <a href="{% url 'login:sign_in' %}">sign_in</a><br>

{% endblock %}

bestshaper/templates/sign_in.html
{% extends "base.html" %}

{% block body %}
sign_in
{% endblock %}

bestshaper/templates/sign_up.html
{% extends "base.html" %}

{% block body %}
<form action="" method="POST">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

bestshaper/templates/sign_up_done.html
{% extends "base.html" %}

{% block body %}
sing_up_done
{% endblock %}